version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: taskly-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - taskly-backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskly-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - taskly-backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskly-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - node_modules:/frontend/app/node_modules
    networks:
      - taskly-frontend-network

volumes:
  db_data:
  node_modules:

networks:
  taskly-backend-network:
  taskly-frontend-network:
